title: Amy Hoo
description: Amy is a programmer focusing on DevOps and  python language, living in Shanghai .
show_downloads: false
google_analytics: true
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
  
plugins:
  - jemoji
  
# About/contact
author:
  name: Amy
  description: A passionate pythoner.
  #gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    #linkedin:  https://www.linkedin.com/in/{{}}
    github:    https://github.com/amyhoo
    # facebook:  <hide>
    #twitter:   https://twitter.com/Li_Zhihao
    #weibo:     http://weibo.com/41173780
    #email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:      
      comment: intensedebate
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: category  
  -      
    scope:
      path: ""
      type: "tag"
    values:
      layout: tag  

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Categories:           
    - '/categories/'
    - { devOps: '/category/devOps/' }
    - { database: '/category/database/' }
    - { webApp: '/category/webApp/' }
    - { webServer: '/category/webServer/' }
    - { payment: '/category/payment/' }
  Tags:          
    - '/tags/'
  Github Project: 
    - 'http://amyhoo.github.io/'
                  
# Collections
collections:
 category:
  output: true
  permalink: /:collection/:title
 tag:
  output: true
  permalink: /:collection/:title  