title: Amy Hoo
description: Amy is a female programmer focus on DevOps and  python language, living in Shanghai .
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM