title: Amy Hoo
description: Amy is a programmer focus on DevOps and  python language, living in Shanghai .
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: category  
  -      
    scope:
      path: ""
      type: "tag"
    values:
      layout: tag          
# Collections
collections:
 category:
  output: true
  permalink: /:collection/:title
 tag:
  output: true
  permalink: /:collection/:title  