title: Amy Hoo
description: Amy is a female programmer focus on DevOps and  python language, living in Shanghai .
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
  
# Collections
collections:
 category:
  output: true
  permalink: /:collection/:title
 tag:
  output: true
  permalink: /:collection/:title  
  
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"  
    scope:
      path: ""
      type: tag
    values:
      layout: "tag"        